### ISSUE TITLE
Unable to fold with exception 'supported' not found

### ISSUE THREAD

**Issue by MR-Jarble** [FoldingAtHome/fah-web-client-bastet#137] opened 2024-02-10 01:56 UTC
```
*********************** Log Started 2024-02-10T01:52:58Z ***********************
01:52:58:I1:*********************** Folding@home Client ***********************
01:52:58:I1: Version: 8.3.4
01:52:58:I1: Author: Joseph Coffland <joseph@cauldrondevelopment.com>
01:52:58:I1: Org: foldingathome.org
01:52:58:I1: Copyright: 2023-2024, foldingathome.org
01:52:58:I1: Homepage: https://foldingathome.org/
01:52:58:I1: License: GPL-3.0-or-later
01:52:58:I1: URL: https://beta.foldingathome.org/
01:52:58:I1: Date: Feb 7 2024
01:52:58:I1: Time: 10:49:33
01:52:58:I1: Revision: 432ec23c0cad21b0d889fe6cfabfb694fa6440e3
01:52:58:I1: Branch: master
01:52:58:I1: Compiler: Visual C++
01:52:58:I1: Options: $( /TP $) /std:c++14 /nologo /EHa /wd4297 /wd4103 /O2
01:52:58:I1: /Zc:throwingNew /MT
01:52:58:I1: Platform: win32 10
01:52:58:I1: Bits: 64
01:52:58:I1: Mode: Release
01:52:58:I1: Args: --open-web-control
01:52:58:I1: Config: C:\ProgramData\FAHClient\config.xml
01:52:58:I1:****************************** CBang ******************************
01:52:58:I1: Version: 1.7.2
01:52:58:I1: Author: Joseph Coffland <joseph@cauldrondevelopment.com>
01:52:58:I1: Org: Cauldron Development LLC
01:52:58:I1: Copyright: Cauldron Development LLC, 2003-2024
01:52:58:I1: Homepage: https://cauldrondevelopment.com/
01:52:58:I1: License: LGPL-2.1-or-later
01:52:58:I1: Date: Feb 7 2024
01:52:58:I1: Time: 10:48:58
01:52:58:I1: Revision: f07e7b0ea470bfa8c73d253164056ce63d3d3bca
01:52:58:I1: Branch: master
01:52:58:I1: Compiler: Visual C++
01:52:58:I1: Options: $( /TP $) /std:c++14 /nologo /EHa /wd4297 /wd4103 /O2
01:52:58:I1: /Zc:throwingNew /MT
01:52:58:I1: Platform: win32 10
01:52:58:I1: Bits: 64
01:52:58:I1: Mode: Release
01:52:58:I1:***************************** System ******************************
01:52:58:I1: CPU: AMD EPYC 7713 64-Core Processor
01:52:58:I1: CPU ID: AuthenticAMD Family 25 Model 1 Stepping 1
01:52:58:I1: CPUs: 256
01:52:58:I1: Memory: 511.82GiB
01:52:58:I1:Free Memory: 495.48GiB
01:52:58:I1: OS Version: 10.0
01:52:58:I1:Has Battery: false
01:52:58:I1: On Battery: false
01:52:58:I1: Hostname: Render-Server
01:52:58:I1: UTC Offset: -5
01:52:58:I1: PID: 10276
01:52:58:I1: CWD: C:\ProgramData\FAHClient
01:52:58:I1: Exec: C:\Program Files\FAHClient\FAHClient.exe
01:52:58:I1:*******************************************************************
01:52:58:I2:<config>
01:52:58:I2: <!-- Resource Settings -->
01:52:58:I2: <cpus v='32'/>
01:52:58:I2:
01:52:58:I2: <!-- User Information -->
01:52:58:I2: <passkey v='*****'/>
01:52:58:I2: <team v='37726'/>
01:52:58:I2: <user v='jarble'/>
01:52:58:I2:</config>
01:52:58:I1:Opening Database
01:52:58:I1:F@H ID = UraQSg20ordWTB3CrfNQQM4ZZ1mmQcEGh5k13KXWnY8
01:52:58:I3:Loading default group
01:52:58:I3:Loading default resource group
01:52:58:I1:Listening for HTTP on 127.0.0.1:7396
01:52:58:I3:Loaded 0 wus.
01:52:58:I1:Started Windows systray control
01:52:58:E :CUDA not supported: Failed to open dynamic library 'nvcuda.dll': The specified module could not be found.
01:52:58:I3:gpus = {
01:52:58:I3: "gpu:-125:00:00": {
01:52:58:I3: "vendor": 4098,
01:52:58:I3: "type": "amd",
01:52:58:I3: "description": "gfx1100",
01:52:58:I3: "opencl": {"platform": 0, "device": 1, "compute": "2.0", "driver": "3608.0"}
01:52:58:I3: },
01:52:58:I3: "gpu:-61:00:00": {
01:52:58:I3: "vendor": 4098,
01:52:58:I3: "type": "amd",
01:52:58:I3: "description": "gfx1100",
01:52:58:I3: "opencl": {"platform": 0, "device": 0, "compute": "2.0", "driver": "3608.0"}
01:52:58:I3: },
01:52:58:I3: "gpu:131:00:00": {"vendor": 4098, "device": 29772, "type": "amd", "supported": false, "description": "Navi 31 [Radeon RX 7900XT/XTX/GRE]"},
01:52:58:I3: "gpu:195:00:00": {"vendor": 4098, "device": 29772, "type": "amd", "supported": false, "description": "Navi 31 [Radeon RX 7900XT/XTX/GRE]"}
01:52:58:I3:}
01:52:58:E :Exception: Key 'supported' not found
01:52:58:I3:Connecting to node1.foldingathome.org:443
01:52:59:I1:OUT1:> GET wss://node1.foldingathome.org/ws/client HTTP/1.1
01:52:59:I1:OUT1:< HTTP/1.1 101 HTTP_SWITCHING_PROTOCOLS
01:52:59:I1:Logging into node account
01:53:46:E :Exception: Key 'supported' not found
01:53:51:E :Exception: Key 'supported' not found
01:54:17:E :Exception: Key 'supported' not found
```

**Comment by jcoffland** [comment] 2024-02-12 10:35
This is caused by a GPU detection problem.  F@H is showing 4 GPUs but in fact there are only 2.  The ones with IDs ``-125:00:00`` and ``-61:00:00`` are incorrect. These IDs should never be negative.  It's a signed/unsigned integer problem.  This causes an unusual situation in the GPU configuration which leads to ``Exception: Key 'supported' not found``.

This will be fixed in v8.3.5.  Coming soon.

**Comment by MR-Jarble** [comment] 2024-02-14 04:10
would this also cause the cpu to not fold?

**Comment by jcoffland** [comment] 2024-02-14 13:29
Maybe.

**Comment by jcoffland** [comment] 2024-05-25 11:30
Fix in latest alpha releases.

**Closed by jcoffland** 2024-05-25 11:30 UTC
Labels: bug
