### ISSUE TITLE
FAH v8.1.3 on Windows, Nvidia GPU running in OpenCL mode and not CUDA

### ISSUE THREAD

**Issue by Hou5e** [FoldingAtHome/fah-web-client-bastet#47] opened 2022-11-15 11:13 UTC
FAH v8.1.3 on Windows, Nvidia 3080 LHR GPU error:
```
09:03:23:I1:WU3: Configuring platform CUDA
09:03:24:I1:WU3:Failed to create CUDA context:
09:03:24:I1:WU3:Error compiling program: nvrtc: error: invalid value for --gpu-architecture (-arch)
```
Please close this if that was by design. I'm guessing this was due to OpenMM v7.5.1 being used instead of v7.7.0, like in the current FAH v7.6.21.

[log_2022-11-15_01.txt](https://github.com/FoldingAtHome/fah-web-client-bastet/files/10012068/log_2022-11-15_01.txt)
[log_2022-11-15_02.txt](https://github.com/FoldingAtHome/fah-web-client-bastet/files/10012069/log_2022-11-15_02.txt)

**Comment by jcoffland** [comment] 2022-11-15 12:03
This problem was discussed here: https://foldingforum.org/viewtopic.php?t=36595

I'm closing this because it's not an issue with fah-web-client-bastet.

**Closed by jcoffland** 2022-11-15 12:03 UTC

**Comment by Hou5e** [comment] 2022-12-22 16:05
[FAHv7-Log.txt](https://github.com/FoldingAtHome/fah-web-client-bastet/files/10288302/FAHv7-Log.txt)
FAH v7 log file for comparison using CUDA on the Nvidia 3080 card


[log-20221221-125110.txt](https://github.com/FoldingAtHome/fah-web-client-bastet/files/10288349/log-20221221-125110.txt)
FAH v8.1.4 log file won't use CUDA, and only uses OpenCL

**Comment by jcoffland** [comment] 2022-12-22 16:50
I think the problem is the OpenMM core version.  For v8 it's using OpenMM core 0.0.15.  For v7 it's 0.0.20.  I need to package 0.0.20 for v8.

**Comment by jcoffland** [comment] 2022-12-22 17:09
I updated the core version but that didn't fix it.

**Comment by jcoffland** [comment] 2022-12-22 18:00
I'm convinced this does not have anything to do with the client version.  It has something to do with the project itself.
