### ISSUE TITLE
Command line control of the local client

### ISSUE THREAD

**Issue by Adanorm** [FoldingAtHome/fah-web-client-bastet#132] opened 2024-02-08 19:21 UTC
Maybe already requested or done,

command line control to start, stop, finishing work.

**Comment by kbernhagen** [comment] 2024-02-09 10:54
Looks like duplicate of https://github.com/FoldingAtHome/fah-client-bastet/issues/119

**Comment by jcoffland** [comment] 2024-02-09 12:32
Indeed, this is a duplicate and belongs to fah-client-bastet.

**Closed by jcoffland** 2024-02-09 12:32 UTC
