### ISSUE TITLE
Restarting Client, the WU ETA completion is inaccurate

### ISSUE THREAD

**Issue by Hou5e** [FoldingAtHome/fah-web-client-bastet#57] opened 2022-11-28 15:10 UTC
After restarting the Client, with a partially completed WU (like at 50% or more completed), the WU ETA completion is inaccurate and says 5-15 minutes left for about 1 hour, on a 2 hour long GPU WU. The displayed ETA time does odd things, like: stops, and jumps around.

**Comment by jcoffland** [comment] 2022-11-29 12:09
The ETA is computed as: ``run_time_estimate * (1 - estimated_progress)``.  Run time is estimated from first from previous runs of the same WU, second from timings of previous frames and finally from the ``timeout`` if no previous information is available.  Progress is estimated based on the number of frames completed plus an estimate of how long the current frame has progressed.  This can lead to inaccuracy in several ways.

A big part of the problem is that current cores don't give very accurate progress information.  This should improve with future core releases.  The one thing we can measure fairly accurately is how much time a WU has run for.  But performance can vary especially if other tasks are running on the same CPUs/GPUs.

**Comment by jcoffland** [comment] 2022-11-29 12:13
Moving to fah-client-bastet https://github.com/FoldingAtHome/fah-client-bastet/issues/57

**Closed by jcoffland** 2022-11-29 12:13 UTC
Labels: bug
