### ISSUE TITLE
Upgrading from v8.1 -> v8.2 -> v8.3 mixes up resource groups

### ISSUE THREAD

**Issue by Hou5e** [FoldingAtHome/fah-web-client-bastet#112] opened 2023-12-28 07:19 UTC
These issues are probably not common for new installs and might just be WIP issues:
In FAH v8.3.0 from source, on Mint21.1 (Ubuntu 22.04), updating from FAH v8.2.4 with Resource Groups, you can end up with your previous settings and new settings merged together (or not cleaned out). In FAH v8.1, I had 0 CPUs & 0 GPUs for the Default RG, and had each GPU in separate RGs. For FAH v8.2, the GPUs got put in the Default Resource group and were gone/hidden in the UI. The RG's are back in FAH v8.3, but are in both places the Default and in the RGs, which can cause the Start 'Fold'ing overall control to get WUs for too many devices (2x):
![image](https://github.com/FoldingAtHome/fah-web-client-bastet/assets/20870053/3eb9fe7e-dbba-4d18-ba2e-9e49454cf6ac)
(Are there any plans for this?): Most of the time you really would want 'Per WU' controls for {Start/Pause/Finish}, and not need Resource Groups, something more like:
![image](https://github.com/FoldingAtHome/fah-web-client-bastet/assets/20870053/73a5e6b3-5acd-4d88-ab5f-292650bdaaac)

On a different PC, with a RG from updating to the newer FAH v8.3:
![image](https://github.com/FoldingAtHome/fah-web-client-bastet/assets/20870053/ac582a89-fc2f-40e0-a88d-2b5c31e36902)

If the resource group '/RG1' is deleted and re-added, it looks good.
Or, just deleting the RG, it looks good.

But in either case the GPU controls in the settings are gone:
![image](https://github.com/FoldingAtHome/fah-web-client-bastet/assets/20870053/578165e2-009d-49cc-b4d8-bd3f94ab452e)

You can delete a RG when FAH is not Folding. But, if FAH is Folding (or Paused), and you try to delete a non-running RG, you get an error saving those settings: `06:47:02:E :WS59:Exception: Closing Websocket: Can't dereference NULL pointer!` and the RG isn't deleted.

**Comment by jcoffland** [comment] 2023-12-28 12:10
I'm seeing four issues here:

1. Upgrading from v8.1 with RGs to v8.2 to v8.3 results in messed up RGs.
2. Request for per WU Fold/Pause.
3. GPU controls are missing from RG settings.
4. Deleting RG which has a WU causes ``Exception: Closing Websocket: Can't dereference NULL pointer!``

**Comment by jcoffland** [comment] 2023-12-28 12:30
We need RGs for other reasons so 2. wont be done.
3. is fixed by a recent commit.

**Comment by jcoffland** [comment] 2023-12-29 16:16
Is 4. still an issue?  I cannot reproduce it.

**Comment by Hou5e** [comment] 2023-12-30 11:30
For your comment about number 2: I would like both Per WU controls and RGs (not Per WU controls to eliminate RGs). Mostly, so I don't need to use RGs, unless I need to, which I wouldn't if there was Per WU controls. Per WU controls will still work with future WUs that use more than 1 resource in your PC.

It looks like fixing 3 also fixed 4. I can't reproduce it now.

For 1, I would just make a note of it when this version is released for alpha testing. It's easy enough to pause WUs and fix the issue with the resources. Most people would be updating from v8.1, so this shouldn't be a problem.

**Comment by jcoffland** [comment] 2024-05-25 11:38
I don't think this is worth fixing at this point.

**Closed by jcoffland** 2024-05-25 11:38 UTC
Labels: bug
